# Generated by Django 2.2.28 on 2024-02-25 03:44

import django.core.validators
from django.db import migrations, models
import django_unixdatetimefield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_nuber', message='Phone number must be forman: 7XXXXXXXXXX', regex='^(7+([0-9]){10})$')])),
                ('mobile_operator_code', models.CharField(max_length=3)),
                ('tag', models.CharField(max_length=50)),
                ('time_zone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', django_unixdatetimefield.fields.UnixDateTimeField()),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
